---
apiVersion: v1
kind: Pod
metadata:
  name: nginxtest20190918
  namespace: acc-wh-terry2
  labels:
    app: nginxtest20190918
spec:
  containers:
    - name: nginxtest20190918
      image: 192.168.200.112/jenkins_images/nginx-test:<BUILD_TAG>
      ports:
        - containerPort: 80
          hostPort: 31601
      volumeMounts:
        - name: nginx-data
          mountPath: /usr/share/nginx/html
#       - name: nginx-etc
#         mountPath: /etc/nginx
  volumes:
    - name: nginx-data
      persistentVolumeClaim:
          claimName: ngnix-test
#   - name: nginx-etc
#     persistentVolumeClaim:
#         claimName: ngnix-test
  nodeSelector:
    labelName: nginx-test-node-n01