---
apiVersion: v1
kind: Pod
metadata:
  name: nginxtest20190918
  namespace: acc-wh-terry2
  labels:
    app: nginxtest20190918
spec:
  containers:
    - name: nginxtest20190918
      image: yswwhf/nginx-test:<BUILD_TAG>
      ports:
        - containerPort: 80
          hostPort: 31601